- name: Get VM information
  hosts: localhost
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ azure_sub_id }}"
  tasks:

    - name: Install the application package (RedHat)
      shell: pip3 install azure-cli

    - name: Azure Login
      shell: az login --service-principal -u {{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }} -p {{ lookup('ansible.builtin.env', 'AZURE_SECRET') }} --tenant {{ lookup('ansible.builtin.env', ' AZURE_TENANT') }}

    - name: Set Subscription ID
      shell: az account set -s "{{ azure_sub_id }}"

    - name: Get facts by backup protection
      shell: az backup protection check-vm --resource-group "{{ rg_name }}" --vm "{{ vm_name }}"
      register: vm_r_info
    - name: Print
      debug:
       var: vm_r_info

    - name: Get Recovery Vault Name
      set_fact:
        recovery_vault_name: "{{ vm_r_info.split('/') | last }}"
      when: vm_r_info.stdout is defined
