- name: Get VM information
  hosts: localhost
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ azure_sub_id }}"
  tasks:
    - name: Create local azure-cli repository information
      shell: sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'

    - name: Install Azure CLi
      yum:
        name: "azure-cli"
        state: present

    - name: Verify installed version
      shell: az --version
      register: azureVersion

    - debug:
        msg: "{{azureVersion.stdout}}"  
        
    - name: Get facts by resource name
      shell: az backup protection check-vm --resource-group dchan-rg --vm vm30
      register: vm_r_info
    - name: Print
      debug:
       var: vm_r_info
       
    - name: Get facts by Virtual Machine name
      azure_rm_virtualmachine_info:
        name: "{{ vm_name }}"
        resource_group: "{{ rg_name }}"
      register: vm_info
    - name: Print
      debug:
       var: vm_info
    
    - name: Verify Resource group
      azure_rm_resourcegroup_info:
        name: "{{ rg_name }}"
      register: rg
    
    - name: Print
      debug:
        #msg: "{{ rg.resourcegroups.0.id }}"
        var: rg.resourcegroups.0.id
    - name: Get Recovery Vault Name
      set_fact:
        recovery_vault_name: "{{ vm_info.instance.resources[0].properties.storageProfile.recoveryServicesVaultId | split('/') | last }}"
      when: vm_info.instance.resources[0].properties.storageProfile.recoveryServicesVaultId is defined
