- name: Get VM information
  hosts: localhost
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ azure_sub_id }}"
  vars:
    az_token_url: "https://login.microsoftonline.com/{{ lookup('ansible.builtin.env', ' AZURE_TENANT') }}/oauth2/token"
    az_token_body: >
        resource=https://management.core.windows.net/
        &client_id={{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}
        &grant_type=client_credentials
        &client_secret={{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}
  tasks:

    - name: Install the application package (RedHat)
      shell: pip3 install azure-cli

    - name: Azure Login
      shell: az login --service-principal -u {{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }} -p {{ lookup('ansible.builtin.env', 'AZURE_SECRET') }} --tenant {{ lookup('ansible.builtin.env', ' AZURE_TENANT') }}

    - name: Set Subscription ID
      shell: az account set -s "{{ azure_sub_id }}"

    - name: Get facts by backup protection
      shell: az backup protection check-vm --resource-group "{{ rg_name }}" --vm "{{ vm_name }}"
      register: vm_r_info

    - name: Fetch Token information
      ansible.builtin.uri:
        url: "{{ az_token_url }}"
        method: POST
        body: "{{ az_token_body }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        status_code: 200
      register: login

    - name: Fetch Recovery Services Vault information
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_sub_id }}/resourceGroups/{{ rg_name }}/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01"
        method: GET
        headers:
          Authorization: "Bearer {{ login.json.access_token }}"
          Content-Type: "application/json"
        status_code: 200
        return_content: yes
      register: vault_info_response
