---
- hosts: Databases
  vars:
    db_packages:
      - mariadb-server
      - MySQL-python
    db_service: mariadb
    src_file: "http://192.168.122.30/static/my.cnf.template"
    dst_file: /etc/my.cnf
    mysql_password: redhat

  tasks:
  - name: Install "{{ db_packages }}" package
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ db_packages }}"
    notify:
      - start_service
  - name: Download and install "{{ dst_file }}"
    get_url:
      url: "{{ src_file }}"
      dest: "{{ dst_file }}"
      owner: mysql
      group: mysql
      force: yes
      validate_certs: no
    notify:
      - restart_service
      - set_password
      - open_firewall

  handlers:
  - name: start_service
    service:
      name: "{{ db_service }}"
      state: started

  - name: restart_service
    service:
      name: "{{ db_service }}"
      state: restarted

  - name: set_password
    mysql_user:
      name: root
      password: "{{ mysql_password }}"

  - name: open_firewall
    firewalld:
      immediate: yes
      permanent: true
      state: enabled
      port: 3306/tcp

