---
- name: POC Item 8 Password Reset on RHEL
  hosts: all
  vars:
     uusername: null
     upassword: null
     cpassword: null
  tasks:
    - name: Check Password
      fail:
         msg: "Password not match!"
      when: upassword != cpassword

    - name: Check if user exists
      shell: /usr/bin/getent group | awk -F":" '{print $1}'
      register: etc_groups

    - name: Exit if user exists
      fail:
         msg: "User doesn't exist!"
      when: uusername not in etc_groups.stdout_lines

    - name: Password Reset
      user:
         name: "{{ uusername }}"
         password: "{{ upassword | password_hash('sha512') }}"
