---
- name: Windows Patch Install
  hosts: windows
  tasks:
  - name: Download Patch
    win_get_url:
      url: http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/09/windows8.1-kb4516067-x64_cea63653326697b8aca38b2c8861f62971bc437b.msu
      dest: C:\Windows8.1-kb4516067-x64-2012R2.msu
  - name: Stop Windows Service
    win_service:
      name: VSS
      state: stopped
  - name: Install Patch
    win_hotfix:
      source: C:\Windows8.1-kb4516067-x64-2012R2.msu
      hotfix_kb: KB4516067
      state: present
    register: hotfix_install
  - win_reboot:
    when: hotfix_install.reboot_required
  - name: Restart Windows Service
    win_service:
      name: VSS
      state: started
