---
- name: Windows Patch Install
  hosts: windows
  tasks:
  - name: Download Patch
    win_get_url:
      url: https://download.microsoft.com/download/7/D/0/7D05B8C7-EBA4-452C-9220-B5ED46DE275D/IE11-Windows6.1-KB3003057-x86.msu
      dest: C:\KB2937592.msu
  - name: Stop Windows Service
    win_service:
      name: VSS
      state: stopped
  - name: Install Patch
    win_hotfix:
      source: C:\KB2937592.msu
      hotfix_kb: KB2937592
      state: absent
    register: hotfix_install
  - win_reboot:
    when: hotfix_install.reboot_required
  - name: Restart Windows Service
    win_service:
      name: VSS
      state: started
