---
- name: Windows Patch Install
  hosts: windows
  tasks:
  - name: Download Patch
    win_get_url:
      url: http://download.microsoft.com/download/D/B/1/DB1F29FC-316D-481E-B435-1654BA185DCF/Windows8.1-KB2937592-x64.msu
      dest: C:\KB2937592.msu
  - name: Stop Windows Service
    win_service:
      name: VSS
      state: stopped
  - name: Install Patch
    win_hotfix:
      source: C:\KB2937592.msu
      hotfix_kb: KB2937592
      state: absent
    register: hotfix_install
  - win_reboot:
    when: hotfix_install.reboot_required
  - name: Restart Windows Service
    win_service:
      name: VSS
      state: started
