---
- name: POC Item 2 Hardening
  hosts: all
  tasks:
    - name: Ensure AIDE is installed
      yum:
         name: aide
         state: present
      ignore_errors: True

    - name: Ensure permissions on /etc/motd are configured
      file:
         dest: /etc/motd
         state: file
         owner: root
         group: root
         mode: 0644

    - name: Ensure PAM variable minlen is set accordingly
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*minlen
        line: minlen = 3
